version: "3"

services:
  php-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/www.conf:/etc/php-fpm.d/www.conf

    image: trang-le-nginx-php
    ports:
      - "8080:80"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d/
networks:
  internal:
    driver: bridge
